### ISSUE TITLE
Travis CI build failing on 14.04 LTS

### ISSUE THREAD

**Issue by brettsheffield** [librestack/librecast#1]
```
$ make
cd src && make
make[1]: Entering directory `/home/travis/build/brettsheffield/librecast/src'
gcc -Wall -Werror -g -c args.c -pthread -lncurses
gcc -Wall -Werror -g -c config.c -pthread -lncurses
gcc -Wall -Werror -g -c errors.c -pthread -lncurses
gcc -Wall -Werror -g -c log.c -pthread -lncurses
gcc -Wall -Werror -g -c misc.c -pthread -lncurses
gcc -Wall -Werror -g -fpic -c pid.c -pthread -lncurses
gcc -Wall -Werror -g -c socket.c -pthread -lncurses
gcc -Wall -Werror -g -c daemon.c -pthread -lncurses
gcc -Wall -Werror -g -c commands.c -pthread -lncurses
gcc -Wall -Werror -g -c controller.c -pthread -lncurses
gcc -Wall -Werror -g -c handler.c -pthread -lncurses
gcc -Wall -Werror -g -c net.c -pthread -lncurses
In file included from net.c:3:0:
/usr/include/linux/in6.h:30:8: error: redefinition of ‘struct in6_addr’
/usr/include/netinet/in.h:198:8: note: originally defined here
/usr/include/linux/in6.h:46:8: error: redefinition of ‘struct sockaddr_in6’
/usr/include/netinet/in.h:239:8: note: originally defined here
/usr/include/linux/in6.h:54:8: error: redefinition of ‘struct ipv6_mreq’
/usr/include/netinet/in.h:275:8: note: originally defined here
net.c: In function ‘net_multicast_listen’:
net.c:121:5: error: ‘struct ipv6_mreq’ has no member named ‘ipv6mr_interface’
make[1]: *** [net.o] Error 1
make[1]: Leaving directory `/home/travis/build/brettsheffield/librecast/src'
make: *** [src] Error 2
The command "make" exited with 2.
```

**Comment by brettsheffield** [comment]
It's likely many of the structures and function calls I'm using require a very recent kernel (I'm developing and testing on 4.9).  Unfortunately, Travis CI only supports the rather ancient 14.04 LTS in their default docker build environment so build tests are going to fail until this is fixed.  Once the base design is laid down I'll look at extending to compatibility to (at least) all currently supported LTS server versions.

**Comment by brettsheffield** [comment]
Tested build on a 14.04 LTS VM and it builds without error:

```
$ make clean
rm -f *.o librecastd lctl nodewatch liblibrecast.so
bacs@grumio.bravo:~/librecast/src$ make
gcc -Wall -Werror -g -c args.c -pthread -lncurses
gcc -Wall -Werror -g -c config.c -pthread -lncurses
gcc -Wall -Werror -g -c errors.c -pthread -lncurses
gcc -Wall -Werror -g -c log.c -pthread -lncurses
gcc -Wall -Werror -g -c misc.c -pthread -lncurses
gcc -Wall -Werror -g -fpic -c pid.c -pthread -lncurses
gcc -Wall -Werror -g -c socket.c -pthread -lncurses
gcc -Wall -Werror -g -c daemon.c -pthread -lncurses
gcc -Wall -Werror -g -c commands.c -pthread -lncurses
gcc -Wall -Werror -g -c controller.c -pthread -lncurses
gcc -Wall -Werror -g -c handler.c -pthread -lncurses
gcc -Wall -Werror -g -c net.c -pthread -lncurses
gcc -Wall -Werror -g -c signals.c -pthread -lncurses
gcc -Wall -Werror -g -o librecastd args.o config.o errors.o log.o misc.o pid.o socket.o daemon.o commands.o controller.o handler.o net.o signals.o -pthread -lncurses
gcc -Wall -Werror -g -c client.c -pthread -lncurses
gcc -Wall -Werror -g -o lctl args.o config.o errors.o log.o misc.o pid.o socket.o client.o -pthread -lncurses
gcc -Wall -Werror -g -c nodewatch.c -pthread -lncurses
gcc -Wall -Werror -g -o nodewatch args.o config.o errors.o log.o misc.o pid.o socket.o nodewatch.o commands.o controller.o handler.o net.o -pthread -lncurses
gcc -Wall -Werror -g -fpic -c librecast.c
gcc -Wall -Werror -g -shared -o liblibrecast.so librecast.o pid.o
```
